resolver: lts-12.6

flags: {}

packages:
- '.'

extra-deps:
- haskus-utils-1.0
- haskus-utils-types-1.0
- haskus-utils-data-1.0
- haskus-utils-variant-1.0
- haskus-binary-1.0
- hsnoise-0.0.2
- git: https://github.com/haskus/haskus-system.git
  commit: e4cbd6f75b945f8dda0d110c1412aca207cecf70

ghc-options:
   "haskus-system": -fobject-code
   "$locals": -fhide-source-paths

compiler: ghc-8.4.3
ghc-variant: bugfix
# allow-newer: true

setup-info:
  ghc:
     linux64-custom-bugfix-tinfo6:
        8.4.3:
           url: "http://haskus.org/downloads/ghc-8.4.3-x86_64-bugfix-linux.tar.xz"
