resolver: https://raw.githubusercontent.com/haskus/haskus-snapshots/master/haskus-10.yaml


flags: {}

packages:
- '.'
  # - location:
  #     git: https://github.com/haskus/haskus-system.git
  #     commit: fd9feb947109ac34d89161721f4858e7a1d821d0
  #   extra-dep: true

extra-deps:
- diagrams-1.4
- diagrams-rasterific-1.4

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code
   "$locals": -fhide-source-paths
