resolver: lts-8.18

flags: {}

packages:
- '.'
- location:
    #git: git@github.com:haskus/haskus-system
    git: /home/hsyl20/travail/code/haskus-system
    commit: e2463198ad034c74c24ff21f2d3d554c2fd61bb2
  extra-dep: true
- location:
    git: /home/hsyl20/travail/code/haskus-binary
    commit: 86c3020532dc0ead052e761bbb97d88ec61a32e6
  extra-dep: true
- location:
    git: /home/hsyl20/travail/code/haskus-utils
    commit: 3e658bf8e6d9b2084ffb36553b23432fb388ee3f
  extra-dep: true
# We need a patched FontyFruity to support accentuated characters correctly.
# Patches have been submitted upstream, so this should ultimately be unnecessary.
- location:
    git: git@github.com:hsyl20/FontyFruity
    commit: 58dca4d1a840f0517c6a90b4285bfd5f06c7891b
  extra-dep: true

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code

extra-deps:
- haskus-binary-0.6.0.0
- haskus-utils-0.7.0.0
