resolver: lts-10.3

flags: {}

packages:
- '.'
- location:
    git: https://github.com/haskus/haskus-system.git
    commit: a2bfc6f8c743da0c77c615ccf590541569c6339e
  extra-dep: true
- location:
    git: https://github.com/haskus/haskus-binary.git
    commit: f2a0e634cb2d9f5d5ec47c24e7209f65b674513b
  extra-dep: true
- location:
    git: https://github.com/haskus/haskus-utils.git
    commit: 041b9421a4e4ff64b9ac0f7ce43ab0d68b879c9a
  extra-dep: true

extra-deps:
- diagrams-1.4
- diagrams-rasterific-1.4

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code
