resolver: lts-15.15
packages:
- 'haskus-system'
- 'haskus-system-build'
- 'haskus-system-tools'
- 'haskus-system-examples'

extra-deps:
   # - haskus-utils-variant-2.6.1
   # - haskus-utils-1.4
   # - haskus-utils-data-1.1.1
   # - haskus-utils-types-1.4.1
   # - haskus-binary-1.4
- hsnoise-0.0.2
- git: https://github.com/haskus/packages.git
  commit: f7fbff7d0fcfaf7bb505bdbabdf02a8d69925f2a
  subdirs:
     - haskus-utils-variant
     - haskus-utils
     - haskus-utils-types
     - haskus-utils-data
     - haskus-utils-compat
     - haskus-binary
     - haskus-web
     - haskus-ui

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors -fobject-code
   "haskus-system": -fobject-code
   # -fobject-code       -- GHCI needs it because of the foreign primops
