resolver: lts-13.1
packages:
- 'haskus-system'
- 'haskus-system-build'
- 'haskus-system-tools'

extra-deps:
- haskus-utils-variant-2.5
- haskus-utils-1.4
- haskus-utils-data-1.1.1
- haskus-utils-types-1.3.1
- haskus-binary-1.2
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- happstack-server-7.5.1.3
  #- git: https://github.com/haskus/haskus-utils.git
  #  commit: 4b00a96cee23ba0bf658834709703368b02f7e30
  #  subdirs:
  #     - haskus-utils-variant
  #     - haskus-utils
  #     - haskus-utils-types
  #     - haskus-utils-data

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "$locals": -fhide-source-paths
   "haskus-system": -fobject-code -freverse-errors
   # -fobject-code       -- GHCI needs it because of the foreign primops
