resolver: lts-13.10

flags: {}

packages:
- '.'

extra-deps:
- haskus-utils-variant-2.6.1
- haskus-utils-1.4
- haskus-utils-data-1.1.1
- haskus-utils-types-1.4.1
- haskus-binary-1.4
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- hsnoise-0.0.2
- git: https://github.com/haskus/haskus-system.git
  commit: 374e70c7bfc5d6ea96110d66c3df508b2c199bd9
  subdirs:
      - haskus-system

ghc-options:
   "haskus-system": -fobject-code
   "$locals": -fhide-source-paths -freverse-errors
