resolver: lts-12.1

flags: {}

packages:
- '.'

extra-deps:
- haskus-utils-1.0
- haskus-utils-types-1.0
- haskus-utils-data-1.0
- haskus-utils-variant-1.0
- haskus-binary-1.0
- hsnoise-0.0.2
- git: https://github.com/haskus/haskus-system.git
  commit: e4cbd6f75b945f8dda0d110c1412aca207cecf70

ghc-options:
   "haskus-system": -fobject-code
   "$locals": -fhide-source-paths
