resolver: lts-8.18

flags: {}

packages:
- '.'
- location:
    git: git@github.com:haskus/haskus-system
    #git: /home/hsyl20/travail/code/haskus-system
    commit: a29623c3366466bc86b27767be35b841d2f6cbca
  extra-dep: true

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code

extra-deps:
- haskus-binary-0.6.0.0
- haskus-utils-0.7.0.0
