resolver: lts-8.15

flags: {}

packages:
- '.'
- location:
    git: git@github.com:haskus/haskus-system
    #git: /home/hsyl20/travail/code/haskus-system
    commit: f611e5936f646db46a37cb2ad6ab57b8b373152b
  extra-dep: true

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code

extra-deps:
- haskus-binary-0.6.0.0
- haskus-utils-0.6.0.0
- JuicyPixels-3.2.7.1
- pqueue-1.3.2
