resolver: lts-8.0

flags: {}

packages:
- '.'
- location:
    git: git@github.com:haskus/haskus-system
    #git: /home/hsyl20/travail/code/haskus-system
    commit: a5dc94144a44979d5afcd6ebf3194ab70bbbd305
  extra-dep: true

ghc-options:
   "haskus-system": -freduction-depth=0 -fobject-code

extra-deps:
- JuicyPixels-3.2.7.1
- pqueue-1.3.2
