resolver: lts-15.15
packages:
- 'haskus-system'
- 'haskus-system-build'
- 'haskus-system-tools'
- 'haskus-system-examples'

extra-deps:
- haskus-binary-1.5
- haskus-utils-1.5
- haskus-utils-compat-1.1
- haskus-utils-data-1.3
- haskus-utils-types-1.5
- haskus-utils-variant-3.0
- hsnoise-0.0.2
- git: https://github.com/haskus/packages.git
  commit: e92231d1b6d70144c7f04cae07b8c3614dde05d2
  subdirs:
     - haskus-web
     - haskus-ui

flags:
   diagrams:
      rasterific: true

extra-package-dbs: []

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors -fobject-code
   "haskus-system": -fobject-code
   # -fobject-code       -- GHCI needs it because of the foreign primops
