resolver: lts-8.0

flags: {}

packages:
- '.'
- location:
    git: git@github.com:haskus/haskus-system
    #git: /home/hsyl20/travail/code/haskus-system
    commit: 33ba0413f2adae33f66f78e51f7e9e52e63758f1
  extra-dep: true

ghc-options:
   "*": -freduction-depth=0 -Wno-redundant-constraints

extra-deps:
- JuicyPixels-3.2.7.1
- pqueue-1.3.2
